update documentation and code
flexitrace/FlexiAI_CycleDetection pull request #2
Opened 2023-09-21 09:16 UTC by AphroDatalyst

2023-09-21 14:08 UTC, pykeras requested changes

2023-09-21 14:08 UTC, pykeras commented on README.md
colab link doesn't work as intended

2023-09-21 14:08 UTC, pykeras commented on rep_count_squat.ipynb
before commit you must, restart kernel and run all cells in orders (not very important but better to do)

2023-09-21 15:33 UTC, AphroDatalyst commented
reviews are fixed

2023-09-24 11:39 UTC, pykeras approved these changes

2023-09-24 11:39 UTC, merged